# we need this file to build
# static data or update it
# on first launch or patch day
apps:
  - script: ./dma/items/getItems.js
    name: 'DMA-getItems'
    instances: 1
    log_date_format: 'DD/MM HH:mm:ss.SSS'
  - script: ./osint/indexing/indexRealms.js
    name: 'OSINT-indexRealms'
    instances: 1
    log_date_format: 'DD/MM HH:mm:ss.SSS'