version: '3.8'
services:
  dma:
    image: ghcr.io/alexzedim/commonwealth:latest
    restart: always
    command: [ 'node', '--max-old-space-size=4096', 'dist/apps/dma/main.js' ]
    deploy:
      replicas: 3
    environment:
      - NODE_ENV=${NODE_ENV}

  auctions:
    image: ghcr.io/alexzedim/commonwealth:latest
    restart: always
    command: [ 'node', 'dist/apps/auctions/main.js' ]
    environment:
      - NODE_ENV=${NODE_ENV}

  contracts:
    image: ghcr.io/alexzedim/commonwealth:latest
    restart: always
    command: [ 'node', 'dist/apps/contracts/main.js' ]
    environment:
      - NODE_ENV=${NODE_ENV}

  valuations:
    image: ghcr.io/alexzedim/commonwealth:latest
    restart: always
    command: [ 'node', 'dist/apps/valuations/main.js' ]
    environment:
      - NODE_ENV=${NODE_ENV}

  gold:
    image: ghcr.io/alexzedim/commonwealth:latest
    restart: always
    command: [ 'node', 'dist/apps/gold/main.js' ]
    environment:
      - NODE_ENV=${NODE_ENV}

  items:
    image: ghcr.io/alexzedim/commonwealth:latest
    restart: always
    command: [ 'node', 'dist/apps/items/main.js' ]
    environment:
      - NODE_ENV=${NODE_ENV}

  pricing:
    image: ghcr.io/alexzedim/commonwealth:latest
    restart: always
    command: [ 'node', 'dist/apps/pricing/main.js' ]
    environment:
      - NODE_ENV=${NODE_ENV}

  wowtoken:
    image: ghcr.io/alexzedim/commonwealth:latest
    restart: always
    command: [ 'node', 'dist/apps/wowtoken/main.js' ]
    environment:
      - NODE_ENV=${NODE_ENV}
