version: '3.8'
services:
  postgres:
    image: postgres:14.7
    container_name: postgres
    restart: always
    networks:
      - cmnw-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  mongo:
    image: mongo:5.0.6
    restart: always
    container_name: mongo
    volumes:
      - ./mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_ROOT_DATABASE}
    ports:
      - '27017-27019:27017-27019'
    networks:
      - cmnw-network

  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis
    command: redis-server --requirepass $REDIS_PASSWORD --appendonly yes
    volumes:
      - redis:/data:rw,z
    ports:
      - '6379:6379'
    networks:
      - cmnw-network

  # Docker Networks
networks:
  # All container connect in a network
  cmnw-network:
    driver: bridge

volumes:
  postgres:
  mongo:
  redis:
