version: '3.8'
services:
  realms:
    image: ghcr.io/alexzedim/osint:latest
    restart: always
    command: [ 'node', 'dist/apps/realms/main.js' ]
    environment:
      - NODE_ENV=${NODE_ENV}
      - KEY=${KEY}

  keys:
    image: ghcr.io/alexzedim/osint:latest
    restart: always
    command: [ 'node', 'dist/apps/keys/main.js' ]
    environment:
      - NODE_ENV=${NODE_ENV}
      - KEY=${KEY}
