version: '3.8'
services:
  dma:
    image: ghcr.io/alexzedim/dma:latest
    restart: always
    command: [ 'node', '--max-old-space-size=4096', 'dist/apps/dma/main.js' ]
    deploy:
      mode: replicated
      replicas: 2
    environment:
      - NODE_ENV=${NODE_ENV}
      - KEY=${KEY}

  auctions:
    image: ghcr.io/alexzedim/dma:latest
    restart: always
    command: [ 'node', 'dist/apps/auctions/main.js' ]
    environment:
      - NODE_ENV=${NODE_ENV}
      - KEY=${KEY}

  gold:
    image: ghcr.io/alexzedim/dma:latest
    restart: always
    command: [ 'node', 'dist/apps/gold/main.js' ]
    environment:
      - NODE_ENV=${NODE_ENV}
      - KEY=${KEY}

  contracts:
    image: ghcr.io/alexzedim/dma:latest
    restart: always
    command: [ 'node', 'dist/apps/contracts/main.js' ]
    environment:
      - NODE_ENV=${NODE_ENV}
      - KEY=${KEY}

  items:
    image: ghcr.io/alexzedim/dma:latest
    restart: always
    command: [ 'node', 'dist/apps/items/main.js' ]
    environment:
      - NODE_ENV=${NODE_ENV}
      - KEY=${KEY}
