version: '3.8'
services:
  realms:
    container_name: realms
    image: ghcr.io/alexzedim/core:latest
    restart: always
    command: [ 'node', 'dist/apps/realms/main.js' ]
    environment:
      - NODE_ENV=${NODE_ENV}
      - KEY=${KEY}

  keys:
    container_name: keys
    image: ghcr.io/alexzedim/core:latest
    restart: always
    command: [ 'node', 'dist/apps/keys/main.js' ]
    environment:
      - NODE_ENV=${NODE_ENV}
      - KEY=${KEY}
