version: '3'
services:
  database:
    image: "mongo"
    container_name: "mongo"
    environment:
      - MONGO_INITDB_DATABASE=conglomerat
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./volumes/mongo:/data/db
    ports:
    - "27017-27019:27017-27019"
