version: '3.8'
services:
  dma:
    image: ghcr.io/alexzedim/dma:latest
    restart: always
    command: [ 'node', '--max-old-space-size=4096', 'dist/apps/dma/main.js' ]
    deploy:
      mode: replicated
      replicas: 2
    env_file:
      - stack.env

  auctions:
    image: ghcr.io/alexzedim/dma:latest
    restart: always
    command: [ 'node', 'dist/apps/market/main.js' ]
    env_file:
      - stack.env

  items:
    image: ghcr.io/alexzedim/dma:latest
    restart: always
    command: [ 'node', 'dist/apps/items/main.js' ]
    env_file:
      - stack.env
