version: '3.8'
services:
  loki:
    container_name: loki
    image: grafana/loki:latest
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    environment:
      GF_PATHS_PROVISIONING: ${GF_PATHS_PROVISIONING}
      GF_AUTH_ANONYMOUS_ENABLED: ${GF_AUTH_ANONYMOUS_ENABLED}
      GF_AUTH_ANONYMOUS_ORG_ROLE: ${GF_AUTH_ANONYMOUS_ORG_ROLE}
      GF_FEATURE_TOGGLES_ENABLE: ${GF_FEATURE_TOGGLES_ENABLE}
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: true
      GF_CHECK_FOR_UPDATES: false
      GF_PLUGINS_ENABLE_ALPHA: false
      GF_ANALYTICS_REPORTING_ENABLED: false
      GF_ANALYTICS_CHECK_FOR_UPDATES: false
      GF_INSTALL_PLUGINS: ""  # Disable automatic plugin installation
    ports:
      - '3000:3000'
    networks:
      - loki

networks:
  loki:
    driver: bridge
