version: '3.8'
services:
  realms:
    container_name: realms
    image: ghcr.io/alexzedim/core:6.1.5
    restart: always
    command: [ 'node', 'dist/apps/realms/main.js' ]
    env_file:
      - stack.env

  keys:
    container_name: keys
    image: ghcr.io/alexzedim/core:6.1.5
    restart: always
    command: [ 'node', 'dist/apps/keys/main.js' ]
    env_file:
      - stack.env

  traefik:
    image: traefik:v3.4
    container_name: traefik
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
