version: '3.8'
services:
  mongo:
    image: mongo:5.0.6
    restart: always
    container_name: mongo
    volumes:
      - ./volumes/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_ROOT_DATABASE}
    ports:
      - '27017-27019:27017-27019'
    networks:
      - cmnw-network

  redis:
    image: redis:7.0-rc-alpine
    restart: always
    container_name: redis
    command: redis-server --requirepass $REDIS_PASSWORD --appendonly yes
    volumes:
      - ./volumes/redis:/data:rw,z
    ports:
      - '6379:6379'
    networks:
      - cmnw-network

  # Docker Networks
networks:
  # All container connect in a network
  cmnw-network:
    driver: bridge
