packages:
  - 'apps/*'
  - 'libs/*'

registries:
  default: 'https://registry.npmjs.org/'
  '@alexzedim': 'https://registry.npmjs.org/'

minimumReleaseAge: 0

allowBuilds:
  '@swc/core': true
  '@scarf/scarf': false
  msgpackr-extract: false
  unrs-resolver: false

overrides:
  reflect-metadata: 0.2.2
  mongoose: 'npm:noop@1.0.0'
