global:
    scrape_interval: 15s
    evaluation_interval: 15s

rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']

    - job_name: 'postgres'
      static_configs:
          - targets: ['postgres_exporter:9187']
      scrape_interval: 30s
      metrics_path: /metrics
