export enum ELASTIC_INDEX_ENUM {
  ENTITY = 'entity',
  MESSAGES = 'message',
  SERVER = 'server',
  CHANNEL = 'channel'
}

export enum CHANNEL_TYPE {
  GUILD_TEXT = 'GUILD_TEXT',
  DM = 'DM',
  GUILD_VOICE = 'GUILD_VOICE',
  GROUP_DM = 'GROUP_DM',
  GUILD_CATEGORY = 'GUILD_CATEGORY',
  GUILD_NEWS = 'GUILD_NEWS',
  GUILD_STORE = 'GUILD_STORE',
  UNKNOWN = 'UNKNOWN',
  GUILD_NEWS_THREAD = 'GUILD_NEWS_THREAD',
  GUILD_PUBLIC_THREAD = 'GUILD_PUBLIC_THREAD',
  GUILD_PRIVATE_THREAD = 'GUILD_PRIVATE_THREAD',
  GUILD_STAGE_VOICE = 'GUILD_STAGE_VOICE',
}
