export enum APP_LABELS {
  A = 'auctions',
  C = 'core',
  CH = 'characters',
  CMNW = 'cmnw',
  CONTRACTS = 'contracts',
  D = 'dma',
  GOLD = 'gold',
  G = 'guilds',
  I = 'items',
  L = 'ladder',
  M = 'market',
  O = 'osint',
  T = 'test',
  V = 'valuations',
  WCL = 'warcraft-logs',
  W = 'wowprogress',
}
