/**
 * MILLING CONVERSIONS - Herb to Pigment
 * Extracted from TradeSkillMaster with comprehensive metadata
 */

import { DMA_SOURCE, EXPANSION_TICKER_ID, PROFESSION_TICKER } from '@app/resources/constants';

// Profession ID for Inscription is 773
const PROF_INSC = PROFESSION_TICKER.get(773) || 'INSC';

export const MILLING = {
  name: PROF_INSC,
  profession: PROF_INSC,
  media: 'https://render-eu.worldofwarcraft.com/icons/56/ability_miling.jpg',
  spellId: 51005,
  methods: [
    // ========================================================================
    // CLASSIC ERA - Common Pigments
    // ========================================================================
    {
      expansion: 'CLSC',
      rank: 1,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Silverleaf', target: 'Alabaster Pigment' },
      description: 'Silverleaf (i:765) → Alabaster Pigment (i:39151) [1 → 0.578]',
      reagents: [{ itemId: 765, quantity: 1 }],
      derivatives: [{ itemId: 39151, quantity: 0.578 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Peacebloom', target: 'Alabaster Pigment' },
      description: 'Peacebloom (i:2447) → Alabaster Pigment (i:39151) [1 → 0.578]',
      reagents: [{ itemId: 2447, quantity: 1 }],
      derivatives: [{ itemId: 39151, quantity: 0.578 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Earthroot', target: 'Alabaster Pigment' },
      description: 'Earthroot (i:2449) → Alabaster Pigment (i:39151) [1 → 0.6]',
      reagents: [{ itemId: 2449, quantity: 1 }],
      derivatives: [{ itemId: 39151, quantity: 0.6 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Mageroyal', target: 'Dusky Pigment' },
      description: 'Mageroyal (i:785) → Dusky Pigment (i:39334) [1 → 0.566]',
      reagents: [{ itemId: 785, quantity: 1 }],
      derivatives: [{ itemId: 39334, quantity: 0.566 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Briarthorn', target: 'Dusky Pigment' },
      description: 'Briarthorn (i:2450) → Dusky Pigment (i:39334) [1 → 0.5765]',
      reagents: [{ itemId: 2450, quantity: 1 }],
      derivatives: [{ itemId: 39334, quantity: 0.5765 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Swiftthistle', target: 'Dusky Pigment' },
      description: 'Swiftthistle (i:2452) → Dusky Pigment (i:39334) [1 → 0.5855]',
      reagents: [{ itemId: 2452, quantity: 1 }],
      derivatives: [{ itemId: 39334, quantity: 0.5855 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Stranglekelp', target: 'Dusky Pigment' },
      description: 'Stranglekelp (i:3820) → Dusky Pigment (i:39334) [1 → 0.6]',
      reagents: [{ itemId: 3820, quantity: 1 }],
      derivatives: [{ itemId: 39334, quantity: 0.6 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Bruiseweed', target: 'Dusky Pigment' },
      description: 'Bruiseweed (i:2453) → Dusky Pigment (i:39334) [1 → 0.6]',
      reagents: [{ itemId: 2453, quantity: 1 }],
      derivatives: [{ itemId: 39334, quantity: 0.6 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Wild Steelbloom', target: 'Golden Pigment' },
      description: 'Wild Steelbloom (i:3355) → Golden Pigment (i:39338) [1 → 0.5765]',
      reagents: [{ itemId: 3355, quantity: 1 }],
      derivatives: [{ itemId: 39338, quantity: 0.5765 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Grave Moss', target: 'Golden Pigment' },
      description: 'Grave Moss (i:3369) → Golden Pigment (i:39338) [1 → 0.5765]',
      reagents: [{ itemId: 3369, quantity: 1 }],
      derivatives: [{ itemId: 39338, quantity: 0.5765 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Kingsblood', target: 'Golden Pigment' },
      description: 'Kingsblood (i:3356) → Golden Pigment (i:39338) [1 → 0.6]',
      reagents: [{ itemId: 3356, quantity: 1 }],
      derivatives: [{ itemId: 39338, quantity: 0.6 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Liferoot', target: 'Golden Pigment' },
      description: 'Liferoot (i:3357) → Golden Pigment (i:39338) [1 → 0.6]',
      reagents: [{ itemId: 3357, quantity: 1 }],
      derivatives: [{ itemId: 39338, quantity: 0.6 }],
    },

    // ========================================================================
    // CLASSIC ERA - Uncommon Pigments
    // ========================================================================
    {
      expansion: 'CLSC',
      rank: 2,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Mageroyal', target: 'Verdant Pigment' },
      description: 'Mageroyal (i:785) → Verdant Pigment (i:43103) [1 → 0.0915]',
      reagents: [{ itemId: 785, quantity: 1 }],
      derivatives: [{ itemId: 43103, quantity: 0.0915 }],
    },
    {
      expansion: 'CLSC',
      rank: 2,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Briarthorn', target: 'Verdant Pigment' },
      description: 'Briarthorn (i:2450) → Verdant Pigment (i:43103) [1 → 0.0915]',
      reagents: [{ itemId: 2450, quantity: 1 }],
      derivatives: [{ itemId: 43103, quantity: 0.0915 }],
    },
    {
      expansion: 'CLSC',
      rank: 2,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Swiftthistle', target: 'Verdant Pigment' },
      description: 'Swiftthistle (i:2452) → Verdant Pigment (i:43103) [1 → 0.1005]',
      reagents: [{ itemId: 2452, quantity: 1 }],
      derivatives: [{ itemId: 43103, quantity: 0.1005 }],
    },
    {
      expansion: 'CLSC',
      rank: 2,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Stranglekelp', target: 'Verdant Pigment' },
      description: 'Stranglekelp (i:3820) → Verdant Pigment (i:43103) [1 → 0.1075]',
      reagents: [{ itemId: 3820, quantity: 1 }],
      derivatives: [{ itemId: 43103, quantity: 0.1075 }],
    },
    {
      expansion: 'CLSC',
      rank: 2,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Bruiseweed', target: 'Verdant Pigment' },
      description: 'Bruiseweed (i:2453) → Verdant Pigment (i:43103) [1 → 0.1075]',
      reagents: [{ itemId: 2453, quantity: 1 }],
      derivatives: [{ itemId: 43103, quantity: 0.1075 }],
    },

    // ========================================================================
    // SHADOWLANDS - Umbral & Luminous Pigments
    // ========================================================================
    {
      expansion: 'SL',
      rank: 1,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Marrowroot', target: 'Umbral Pigment' },
      description: 'Marrowroot (i:168589) → Umbral Pigment (i:173056) [1 → 0.195]',
      reagents: [{ itemId: 168589, quantity: 1 }],
      derivatives: [{ itemId: 173056, quantity: 0.195 }],
    },
    {
      expansion: 'SL',
      rank: 1,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Widowbloom', target: 'Umbral Pigment' },
      description: 'Widowbloom (i:168583) → Umbral Pigment (i:173056) [1 → 0.195]',
      reagents: [{ itemId: 168583, quantity: 1 }],
      derivatives: [{ itemId: 173056, quantity: 0.195 }],
    },
    {
      expansion: 'SL',
      rank: 1,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Nightshade', target: 'Umbral Pigment' },
      description: 'Nightshade (i:171315) → Umbral Pigment (i:173056) [1 → 0.25]',
      reagents: [{ itemId: 171315, quantity: 1 }],
      derivatives: [{ itemId: 173056, quantity: 0.25 }],
    },
    {
      expansion: 'SL',
      rank: 2,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Luminous Pigment', target: 'Widowbloom' },
      description: 'Widowbloom (i:168583) → Luminous Pigment (i:173057) [1 → 0.105]',
      reagents: [{ itemId: 168583, quantity: 1 }],
      derivatives: [{ itemId: 173057, quantity: 0.105 }],
    },
    {
      expansion: 'SL',
      rank: 3,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'First Flower', target: 'Tranquil Pigment' },
      description: 'First Flower (i:187699) → Tranquil Pigment (i:175788) [1 → 0.5]',
      reagents: [{ itemId: 187699, quantity: 1 }],
      derivatives: [{ itemId: 175788, quantity: 0.5 }],
    },

    // ========================================================================
    // DRAGONFLIGHT - Multi-Quality Pigments
    // ========================================================================
    {
      expansion: 'DF',
      rank: 1,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Hochenblume *', target: 'Shimmering Pigment *' },
      description: 'Hochenblume * (i:191460) → Shimmering Pigment * (i:198421) [1 → 0.7]',
      reagents: [{ itemId: 191460, quantity: 1 }],
      derivatives: [{ itemId: 198421, quantity: 0.7 }],
    },
    {
      expansion: 'DF',
      rank: 1,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Hochenblume **', target: 'Shimmering Pigment **' },
      description: 'Hochenblume ** (i:191461) → Shimmering Pigment ** (i:198422) [1 → 0.7]',
      reagents: [{ itemId: 191461, quantity: 1 }],
      derivatives: [{ itemId: 198422, quantity: 0.7 }],
    },
    {
      expansion: 'DF',
      rank: 3,
      profession: PROF_INSC,
      createdBy: DMA_SOURCE.TSM,
      updatedBy: DMA_SOURCE.TSM,
      ticker: PROF_INSC,
      names: { source: 'Hochenblume ***', target: 'Shimmering Pigment ***' },
      description: 'Hochenblume *** (i:191462) → Shimmering Pigment *** (i:198423) [1 → 0.7]',
      reagents: [{ itemId: 191462, quantity: 1 }],
      derivatives: [{ itemId: 198423, quantity: 0.7 }],
    },
  ],
};


