export enum CMNW_ENTITY_ENUM {
  CHARACTERS = 'characters',
  CHARACTERS_PETS = 'characters_pets',
  PETS = 'pets',
  CHARACTERS_MOUNTS = 'characters_mounts',
  MOUNTS = 'mounts',
  CHARACTERS_PROFESSIONS = 'characters_professions',
  PROFESSIONS = 'professions',
  CHARACTERS_GUILDS_MEMBERS = 'characters_guild_members',
  CHARACTERS_PROFILE = 'characters_profile',
  CHARACTERS_RAID_LOGS = 'character_raid_logs',
  GUILDS = 'guilds',
  KEYS = 'keys',
  REALMS = 'realms',
  LOGS = 'logs',
  ITEMS = 'items',
  MARKET = 'market',
  CONTRACTS = 'contracts',
}
