import { Logger } from '@nestjs/common';
import { OSINT_SOURCE, TIME_MS } from '@app/resources/constants';
import { toGuid } from '@app/resources/transformers';
import { charactersQueue } from '@app/resources/queues/characters.queue';
import { JobsOptions } from 'bullmq';

/**
 * Base interface for character job data payload
 * Contains all character-specific data that travels in job.data field
 * Combines database entity, processing options, and API credentials
 */
export interface ICharacterMessageBase {
  // Essential identification
  id?: number;
  guid?: string;
  name: string;
  realm: string;
  region: 'eu';

  // CharactersEntity properties
  realmId?: number;
  realmName?: string;
  guild?: string;
  guildGuid?: string;
  guildId?: number;
  guildRank?: number;
  class?: string;
  race?: string;
  faction?: string;
  level?: number;
  specialization?: string;
  gender?: string;
  lookingForGuild?: string;
  createdAt?: Date;
  updatedAt?: Date;
  lastModified?: Date;
  achievementPoints?: number;
  averageItemLevel?: number;
  equippedItemLevel?: number;
  covenantId?: number;
  mountsNumber?: number;
  petsNumber?: number;
  avatarImage?: string;
  insetImage?: string;
  mainImage?: string;
  statusCode?: number;
  hashA?: string;
  hashB?: string;

  // Processing metadata
  forceUpdate: number;
  createOnlyUnique: boolean;
  iteration?: number;
  updatedBy: OSINT_SOURCE;
  createdBy?: OSINT_SOURCE;

  // BattleNetOptions
  clientId: string;
  clientSecret: string;
  accessToken: string;
}

/**
 * Character Message DTO for BullMQ
 *
 * Comprehensive data transfer object for character jobs with BullMQ.
 * Includes static factory methods for each source with automatic guid generation,
 * validation, and transformation logic.
 *
 * SOURCES:
 * @see fromMythicPlusLadder - Mythic+ ladder data (priority: 7)
 * @see fromPvPLadder - PvP ladder data (priority: 7)
 * @see fromWarcraftLogs - Warcraft Logs raid data (priority: 8)
 * @see fromWowProgressLfg - WoW Progress LFG data (priority: 6)
 * @see fromGuildMaster - Guild master from guild roster (priority: 9)
 * @see fromCharacterIndex - Character database index (priority: 5)
 * @see fromGuildMember - Guild member from guild roster (priority: 3)
 * @see fromMigrationFile - S3 migration file (priority: 2)
 * @see fromCharacterRequest - Direct API request (priority: 10)
 *
 * GUID FORMAT:
 * - Generated by toGuid(name, realm)
 * - Kebab-case, lowercased, trimmed, no spaces
 * - Format: "character-name@realm-slug"
 * - Example: toGuid('Arthas', 'Burning Legion') => 'arthas@burning-legion'
 */
export class CharacterMessageDto {
  public readonly name: string;
  public readonly data: ICharacterMessageBase;
  public readonly opts?: JobsOptions;

  private static readonly characterLogger = new Logger(CharacterMessageDto.name);

  /**
   * Constructor - creates a validated Character Message with BullMQ properties
   * @param name - Queue name (e.g., 'osint.characters')
   * @param data - Character message data
   * @param opts - BullMQ job options (optional)
   */
  constructor(name: string, data: ICharacterMessageBase, opts?: JobsOptions) {
    this.name = name;
    this.data = data;
    this.opts = opts;
  }

  /**
   * Create with auto-generated guid from name and realm
   * @param data - Character data with name and realm
   * @param opts - Optional job options
   * @returns New CharacterMessageDto instance with generated guid
   */
  static create(
    data: Omit<Partial<ICharacterMessageBase>, 'guid'> &
      Pick<ICharacterMessageBase, 'name' | 'realm'>,
    opts?: JobsOptions,
  ): CharacterMessageDto {
    const guid = toGuid(data.name, data.realm);
    const characterData: ICharacterMessageBase = {
      ...data,
      guid,
      createdBy: data.createdBy || data.updatedBy,
    } as ICharacterMessageBase;

    const mergedOpts = {
      ...charactersQueue.defaultJobOptions,
      ...opts,
    };

    const dto = new CharacterMessageDto(
      charactersQueue.name,
      characterData,
      mergedOpts,
    );
    dto.validate(false, 'CharacterMessageDto.create');
    return dto;
  }

  /**
   * Create from Mythic+ Ladder data
   *
   * Priority: 7 (High - user-initiated competitive content)
   */
  static fromMythicPlusLadder(params: {
    id: number;
    name: string;
    realm: string;
    faction: string;
    clientId: string;
    clientSecret: string;
    accessToken: string;
  }): CharacterMessageDto {
    const guid = toGuid(params.name, params.realm);
    const characterData: ICharacterMessageBase = {
      guid,
      id: params.id,
      name: params.name,
      realm: params.realm,
      faction: params.faction,
      forceUpdate: TIME_MS.IMMEDIATE,
      createOnlyUnique: true,
      region: 'eu',
      createdBy: OSINT_SOURCE.MYTHIC_PLUS,
      updatedBy: OSINT_SOURCE.MYTHIC_PLUS,
      clientId: params.clientId,
      clientSecret: params.clientSecret,
      accessToken: params.accessToken,
    };

    const opts: JobsOptions = {
      ...charactersQueue.defaultJobOptions,
      priority: 7,
    };

    const dto = new CharacterMessageDto(guid, characterData, opts);
    dto.validate(false, 'CharacterMessageDto.fromMythicPlusLadder');
    return dto;
  }

  /**
   * Create from PvP Ladder data
   *
   * Priority: 7 (High - user-initiated competitive content)
   */
  static fromPvPLadder(params: {
    name: string;
    realm: string;
    faction: string;
    iteration?: number;
    clientId: string;
    clientSecret: string;
    accessToken: string;
  }): CharacterMessageDto {
    const guid = toGuid(params.name, params.realm);
    const characterData: ICharacterMessageBase = {
      guid,
      name: params.name,
      realm: params.realm,
      faction: params.faction,
      iteration: params.iteration,
      forceUpdate: TIME_MS.IMMEDIATE,
      createOnlyUnique: true,
      region: 'eu',
      createdBy: OSINT_SOURCE.PVP_LADDER,
      updatedBy: OSINT_SOURCE.PVP_LADDER,
      clientId: params.clientId,
      clientSecret: params.clientSecret,
      accessToken: params.accessToken,
    };

    const opts: JobsOptions = {
      ...charactersQueue.defaultJobOptions,
      priority: 7,
    };

    const dto = new CharacterMessageDto(guid, characterData, opts);
    dto.validate(false, 'CharacterMessageDto.fromPvPLadder');
    return dto;
  }

  /**
   * Create from Warcraft Logs raid data
   *
   * Priority: 8 (Very High - official API data)
   */
  static fromWarcraftLogs(params: {
    name: string;
    realm: string;
    clientId: string;
    clientSecret: string;
    accessToken: string;
  }): CharacterMessageDto {
    const guid = toGuid(params.name, params.realm);
    const characterData: ICharacterMessageBase = {
      guid,
      name: params.name,
      realm: params.realm,
      forceUpdate: TIME_MS.IMMEDIATE,
      createOnlyUnique: true,
      region: 'eu',
      createdBy: OSINT_SOURCE.WARCRAFT_LOGS,
      updatedBy: OSINT_SOURCE.WARCRAFT_LOGS,
      clientId: params.clientId,
      clientSecret: params.clientSecret,
      accessToken: params.accessToken,
    };

    const opts: JobsOptions = {
      ...charactersQueue.defaultJobOptions,
      priority: 8,
    };

    const dto = new CharacterMessageDto(guid, characterData, opts);
    dto.validate(false, 'CharacterMessageDto.fromWarcraftLogs');
    return dto;
  }

  /**
   * Create from WoW Progress LFG data
   *
   * Priority: 6 (Medium - community-driven content)
   */
  static fromWowProgressLfg(params: {
    name: string;
    realm: string;
    realmId: number;
    realmName: string;
    clientId: string;
    clientSecret: string;
    accessToken: string;
  }): CharacterMessageDto {
    const guid = toGuid(params.name, params.realm);
    const characterData: ICharacterMessageBase = {
      guid,
      name: params.name,
      realm: params.realm,
      realmId: params.realmId,
      realmName: params.realmName,
      forceUpdate: TIME_MS.IMMEDIATE,
      createOnlyUnique: true,
      region: 'eu',
      createdBy: OSINT_SOURCE.WOW_PROGRESS_LFG,
      updatedBy: OSINT_SOURCE.WOW_PROGRESS_LFG,
      clientId: params.clientId,
      clientSecret: params.clientSecret,
      accessToken: params.accessToken,
    };

    const opts: JobsOptions = {
      ...charactersQueue.defaultJobOptions,
      priority: 6,
    };

    const dto = new CharacterMessageDto(guid, characterData, opts);
    dto.validate(false, 'CharacterMessageDto.fromWowProgressLfg');
    return dto;
  }

  /**
   * Create from Guild Roster (Guild Master)
   *
   * Priority: 9 (Very High - guild leadership data)
   */
  static fromGuildMaster(params: {
    id: number;
    name: string;
    realm: string;
    guild: string;
    guildGuid: string;
    guildId: number;
    guildRank?: number;
    class: string | null;
    race?: string | null;
    faction?: string | null;
    level?: number | null;
    lastModified: Date;
    clientId: string;
    clientSecret: string;
    accessToken: string;
  }): CharacterMessageDto {
    const guid = toGuid(params.name, params.realm);
    const characterData: ICharacterMessageBase = {
      guid,
      id: params.id,
      name: params.name,
      realm: params.realm,
      guild: params.guild,
      guildGuid: params.guildGuid,
      guildId: params.guildId,
      guildRank: params.guildRank,
      class: params.class,
      race: params.race,
      faction: params.faction,
      level: params.level,
      lastModified: params.lastModified,
      forceUpdate: TIME_MS.IMMEDIATE,
      createOnlyUnique: false,
      region: 'eu',
      createdBy: OSINT_SOURCE.GUILD_ROSTER,
      updatedBy: OSINT_SOURCE.GUILD_ROSTER,
      clientId: params.clientId,
      clientSecret: params.clientSecret,
      accessToken: params.accessToken,
    };

    const opts: JobsOptions = {
      ...charactersQueue.defaultJobOptions,
      priority: 9,
    };

    const dto = new CharacterMessageDto(guid, characterData, opts);
    dto.validate(false, 'CharacterMessageDto.fromGuildMaster');
    return dto;
  }

  /**
   * Create from Character Index (database)
   *
   * Priority: 5 (Medium - periodic database indexing)
   */
  static fromCharacterIndex(params: {
    guid: string;
    name: string;
    realm: string;
    iteration: number;
    clientId: string;
    clientSecret: string;
    accessToken: string;
    [key: string]: any;
  }): CharacterMessageDto {
    const { guid, ...rest } = params;
    const characterData: ICharacterMessageBase = {
      guid: params.guid,
      name: params.name,
      realm: params.realm,
      ...rest,
      forceUpdate: TIME_MS.TWENTY_FOUR_HOURS,
      createOnlyUnique: false,
      region: 'eu',
      createdBy: OSINT_SOURCE.CHARACTER_INDEX,
      updatedBy: OSINT_SOURCE.CHARACTER_INDEX,
      clientId: params.clientId,
      clientSecret: params.clientSecret,
      accessToken: params.accessToken,
      iteration: params.iteration,
    };

    const opts: JobsOptions = {
      ...charactersQueue.defaultJobOptions,
      priority: 5,
    };

    const dto = new CharacterMessageDto(guid, characterData, opts);
    dto.validate(false, 'CharacterMessageDto.fromCharacterIndex');
    return dto;
  }

  /**
   * Create from Guild Member (non-guild master)
   *
   * Priority: 3 (Low - regular guild membership updates)
   */
  static fromGuildMember(params: {
    id?: number;
    name: string;
    realm: string;
    realmId: number;
    realmName: string;
    guild: string;
    guildGuid: string;
    guildId: number;
    guildRank: number;
    class: string | null;
    faction?: string | null;
    level?: number | null;
    lastModified: Date;
    clientId: string;
    clientSecret: string;
    accessToken: string;
  }): CharacterMessageDto {
    const guid = toGuid(params.name, params.realm);
    const characterData: ICharacterMessageBase = {
      guid,
      id: params.id,
      name: params.name,
      realm: params.realm,
      realmId: params.realmId,
      realmName: params.realmName,
      guild: params.guild,
      guildGuid: params.guildGuid,
      guildId: params.guildId,
      guildRank: params.guildRank,
      class: params.class,
      faction: params.faction,
      level: params.level,
      lastModified: params.lastModified,
      forceUpdate: TIME_MS.IMMEDIATE,
      createOnlyUnique: true,
      region: 'eu',
      createdBy: OSINT_SOURCE.GUILD_ROSTER,
      updatedBy: OSINT_SOURCE.GUILD_ROSTER,
      clientId: params.clientId,
      clientSecret: params.clientSecret,
      accessToken: params.accessToken,
    };

    const opts: JobsOptions = {
      ...charactersQueue.defaultJobOptions,
      priority: 3,
    };

    const dto = new CharacterMessageDto(guid, characterData, opts);
    dto.validate(false, 'CharacterMessageDto.fromGuildMember');
    return dto;
  }

  /**
   * Create from S3 migration file
   *
   * Priority: 2 (Very Low - bulk data import)
   */
  static fromMigrationFile(params: {
    guid: string;
    clientId: string;
    clientSecret: string;
    accessToken: string;
  }): CharacterMessageDto {
    const [nameSlug, realmSlug] = params.guid.split('@');
    const characterData: ICharacterMessageBase = {
      guid: params.guid,
      name: nameSlug,
      realm: realmSlug,
      region: 'eu',
      forceUpdate: TIME_MS.IMMEDIATE,
      createOnlyUnique: true,
      createdBy: OSINT_SOURCE.OSINT_MIGRATION,
      updatedBy: OSINT_SOURCE.OSINT_MIGRATION,
      clientId: params.clientId,
      clientSecret: params.clientSecret,
      accessToken: params.accessToken,
    };

    const opts: JobsOptions = {
      ...charactersQueue.defaultJobOptions,
      priority: 2,
    };

    const dto = new CharacterMessageDto(characterData.guid, characterData, opts);
    dto.validate(false, 'CharacterMessageDto.fromMigrationFile');
    return dto;
  }

  /**
   * Create from character request (API-driven)
   *
   * Priority: 10 (Very High - user-initiated API requests)
   */
  static fromCharacterRequest(params: {
    name: string;
    realm: string;
    clientId: string;
    clientSecret: string;
    accessToken: string;
  }): CharacterMessageDto {
    const guid = toGuid(params.name, params.realm);
    const characterData: ICharacterMessageBase = {
      guid,
      name: params.name,
      realm: params.realm,
      forceUpdate: TIME_MS.IMMEDIATE,
      createOnlyUnique: false,
      region: 'eu',
      createdBy: OSINT_SOURCE.CHARACTER_REQUEST,
      updatedBy: OSINT_SOURCE.CHARACTER_REQUEST,
      clientId: params.clientId,
      clientSecret: params.clientSecret,
      accessToken: params.accessToken,
    };

    const opts: JobsOptions = {
      ...charactersQueue.defaultJobOptions,
      priority: 10,
    };

    const dto = new CharacterMessageDto(charactersQueue.name, characterData, opts);
    dto.validate(false, 'CharacterMessageDto.fromCharacterRequest');
    return dto;
  }

  /**
   * Validate that required fields are present
   * @param strict - If true, throws errors; if false, logs warnings
   * @param logTag - Optional log tag for warnings (defaults to 'CharacterMessageDto.validate')
   * @throws Error if validation fails and strict is true
   */
  validate(
    strict: boolean = true,
    logTag: string = 'CharacterMessageDto.validate',
  ): void {
    const characterData = this.data;

    if (characterData?.guid && !characterData.guid.includes('@')) {
      const message = `Validation failed: guid '${characterData.guid}' must contain '@' separator`;
      if (strict) {
        throw new Error(message);
      } else {
        CharacterMessageDto.characterLogger.warn({
          logTag,
          message,
          guid: characterData.guid,
        });
      }
    }

    if (
      characterData?.forceUpdate !== undefined &&
      (typeof characterData.forceUpdate !== 'number' ||
        characterData.forceUpdate < 0)
    ) {
      const message = `Validation failed: forceUpdate must be a positive number, got '${characterData.forceUpdate}' for guid '${characterData?.guid || 'unknown'}'`;
      if (strict) {
        throw new Error(message);
      } else {
        CharacterMessageDto.characterLogger.warn({
          logTag,
          message,
          guid: characterData?.guid,
          forceUpdate: characterData?.forceUpdate,
        });
      }
    }

    // Warn about missing optional credentials (non-blocking)
    if (!strict) {
      const credentials = ['clientId', 'clientSecret', 'accessToken'];
      const missingCredentials = credentials.filter(
        (field) => !characterData?.[field] || characterData?.[field] === undefined,
      );
      if (missingCredentials.length > 0) {
        CharacterMessageDto.characterLogger.warn({
          logTag,
          message: `Missing optional credentials: ${missingCredentials.join(', ')}`,
          guid: characterData?.guid,
          missingCredentials,
        });
      }
    }
  }

  /**
   * Create validated instance - throws if validation fails
   */
  static createValidated(
    data: Omit<Partial<ICharacterMessageBase>, 'guid'> &
      Pick<ICharacterMessageBase, 'name' | 'realm'>,
    opts?: JobsOptions,
  ): CharacterMessageDto {
    const dto = CharacterMessageDto.create(data, opts);
    dto.validate();
    return dto;
  }
}
