/**
 * MILLING CONVERSIONS - Herb to Pigment
 * Extracted from TradeSkillMaster with comprehensive metadata
 */

export const MILLING = {
  name: 'INSC',
  profession: 'Inscription',
  media: 'https://render-eu.worldofwarcraft.com/icons/56/ability_miling.jpg',
  spellId: 51005,
  methods: [
    // ========================================================================
    // CLASSIC ERA - Common Pigments
    // ========================================================================
    {
      expansion: 'CLSC',
      rank: 1,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Silverleaf', target: 'Alabaster Pigment' },
      description: 'Mill Silverleaf into Alabaster Pigment (100% success rate, 0.578 average yield)',
      venue: 'Silverleaf (i:765) → Alabaster Pigment (i:39151) [1 → 0.578]',
      reagents: [{ itemId: 765, quantity: 1 }],
      derivatives: [{ itemId: 39151, quantity: 0.578 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Peacebloom', target: 'Alabaster Pigment' },
      description: 'Mill Peacebloom into Alabaster Pigment (100% success rate, 0.578 average yield)',
      venue: 'Peacebloom (i:2447) → Alabaster Pigment (i:39151) [1 → 0.578]',
      reagents: [{ itemId: 2447, quantity: 1 }],
      derivatives: [{ itemId: 39151, quantity: 0.578 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Earthroot', target: 'Alabaster Pigment' },
      description: 'Mill Earthroot into Alabaster Pigment (100% success rate, 0.6 average yield - best source)',
      venue: 'Earthroot (i:2449) → Alabaster Pigment (i:39151) [1 → 0.6]',
      reagents: [{ itemId: 2449, quantity: 1 }],
      derivatives: [{ itemId: 39151, quantity: 0.6 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Mageroyal', target: 'Dusky Pigment' },
      description: 'Mill Mageroyal into Dusky Pigment (100% success rate, 0.566 average yield)',
      venue: 'Mageroyal (i:785) → Dusky Pigment (i:39334) [1 → 0.566]',
      reagents: [{ itemId: 785, quantity: 1 }],
      derivatives: [{ itemId: 39334, quantity: 0.566 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Briarthorn', target: 'Dusky Pigment' },
      description: 'Mill Briarthorn into Dusky Pigment (100% success rate, 0.5765 average yield)',
      venue: 'Briarthorn (i:2450) → Dusky Pigment (i:39334) [1 → 0.5765]',
      reagents: [{ itemId: 2450, quantity: 1 }],
      derivatives: [{ itemId: 39334, quantity: 0.5765 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Swiftthistle', target: 'Dusky Pigment' },
      description: 'Mill Swiftthistle into Dusky Pigment (100% success rate, 0.5855 average yield)',
      venue: 'Swiftthistle (i:2452) → Dusky Pigment (i:39334) [1 → 0.5855]',
      reagents: [{ itemId: 2452, quantity: 1 }],
      derivatives: [{ itemId: 39334, quantity: 0.5855 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Stranglekelp', target: 'Dusky Pigment' },
      description: 'Mill Stranglekelp into Dusky Pigment (100% success rate, 0.6 average yield - best source)',
      venue: 'Stranglekelp (i:3820) → Dusky Pigment (i:39334) [1 → 0.6]',
      reagents: [{ itemId: 3820, quantity: 1 }],
      derivatives: [{ itemId: 39334, quantity: 0.6 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Bruiseweed', target: 'Dusky Pigment' },
      description: 'Mill Bruiseweed into Dusky Pigment (100% success rate, 0.6 average yield - best source)',
      venue: 'Bruiseweed (i:2453) → Dusky Pigment (i:39334) [1 → 0.6]',
      reagents: [{ itemId: 2453, quantity: 1 }],
      derivatives: [{ itemId: 39334, quantity: 0.6 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Wild Steelbloom', target: 'Golden Pigment' },
      description: 'Mill Wild Steelbloom into Golden Pigment (100% success rate, 0.5765 average yield)',
      venue: 'Wild Steelbloom (i:3355) → Golden Pigment (i:39338) [1 → 0.5765]',
      reagents: [{ itemId: 3355, quantity: 1 }],
      derivatives: [{ itemId: 39338, quantity: 0.5765 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Grave Moss', target: 'Golden Pigment' },
      description: 'Mill Grave Moss into Golden Pigment (100% success rate, 0.5765 average yield)',
      venue: 'Grave Moss (i:3369) → Golden Pigment (i:39338) [1 → 0.5765]',
      reagents: [{ itemId: 3369, quantity: 1 }],
      derivatives: [{ itemId: 39338, quantity: 0.5765 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Kingsblood', target: 'Golden Pigment' },
      description: 'Mill Kingsblood into Golden Pigment (100% success rate, 0.6 average yield - best source)',
      venue: 'Kingsblood (i:3356) → Golden Pigment (i:39338) [1 → 0.6]',
      reagents: [{ itemId: 3356, quantity: 1 }],
      derivatives: [{ itemId: 39338, quantity: 0.6 }],
    },
    {
      expansion: 'CLSC',
      rank: 1,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Liferoot', target: 'Golden Pigment' },
      description: 'Mill Liferoot into Golden Pigment (100% success rate, 0.6 average yield - best source)',
      venue: 'Liferoot (i:3357) → Golden Pigment (i:39338) [1 → 0.6]',
      reagents: [{ itemId: 3357, quantity: 1 }],
      derivatives: [{ itemId: 39338, quantity: 0.6 }],
    },

    // ========================================================================
    // CLASSIC ERA - Uncommon Pigments
    // ========================================================================
    {
      expansion: 'CLSC',
      rank: 2,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Mageroyal', target: 'Verdant Pigment' },
      description: 'Mill Mageroyal into Verdant Pigment (42% success rate, 0.0915 average yield)',
      venue: 'Mageroyal (i:785) → Verdant Pigment (i:43103) [1 → 0.0915]',
      reagents: [{ itemId: 785, quantity: 1 }],
      derivatives: [{ itemId: 43103, quantity: 0.0915 }],
    },
    {
      expansion: 'CLSC',
      rank: 2,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Briarthorn', target: 'Verdant Pigment' },
      description: 'Mill Briarthorn into Verdant Pigment (42% success rate, 0.0915 average yield)',
      venue: 'Briarthorn (i:2450) → Verdant Pigment (i:43103) [1 → 0.0915]',
      reagents: [{ itemId: 2450, quantity: 1 }],
      derivatives: [{ itemId: 43103, quantity: 0.0915 }],
    },
    {
      expansion: 'CLSC',
      rank: 2,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Swiftthistle', target: 'Verdant Pigment' },
      description: 'Mill Swiftthistle into Verdant Pigment (46.5% success rate, 0.1005 average yield)',
      venue: 'Swiftthistle (i:2452) → Verdant Pigment (i:43103) [1 → 0.1005]',
      reagents: [{ itemId: 2452, quantity: 1 }],
      derivatives: [{ itemId: 43103, quantity: 0.1005 }],
    },
    {
      expansion: 'CLSC',
      rank: 2,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Stranglekelp', target: 'Verdant Pigment' },
      description: 'Mill Stranglekelp into Verdant Pigment (50% success rate, 0.1075 average yield - best source)',
      venue: 'Stranglekelp (i:3820) → Verdant Pigment (i:43103) [1 → 0.1075]',
      reagents: [{ itemId: 3820, quantity: 1 }],
      derivatives: [{ itemId: 43103, quantity: 0.1075 }],
    },
    {
      expansion: 'CLSC',
      rank: 2,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Bruiseweed', target: 'Verdant Pigment' },
      description: 'Mill Bruiseweed into Verdant Pigment (50% success rate, 0.1075 average yield - best source)',
      venue: 'Bruiseweed (i:2453) → Verdant Pigment (i:43103) [1 → 0.1075]',
      reagents: [{ itemId: 2453, quantity: 1 }],
      derivatives: [{ itemId: 43103, quantity: 0.1075 }],
    },

    // ========================================================================
    // SHADOWLANDS - Umbral & Luminous Pigments
    // ========================================================================
    {
      expansion: 'SL',
      rank: 1,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Marrowroot', target: 'Umbral Pigment' },
      description: 'Mill Marrowroot into Umbral Pigment (65% success rate, 0.195 average yield - best source)',
      venue: 'Marrowroot (i:168589) → Umbral Pigment (i:173056) [1 → 0.195]',
      reagents: [{ itemId: 168589, quantity: 1 }],
      derivatives: [{ itemId: 173056, quantity: 0.195 }],
    },
    {
      expansion: 'SL',
      rank: 1,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Widowbloom', target: 'Umbral Pigment' },
      description: 'Mill Widowbloom into Umbral Pigment (65% success rate, 0.195 average yield - best source)',
      venue: 'Widowbloom (i:168583) → Umbral Pigment (i:173056) [1 → 0.195]',
      reagents: [{ itemId: 168583, quantity: 1 }],
      derivatives: [{ itemId: 173056, quantity: 0.195 }],
    },
    {
      expansion: 'SL',
      rank: 1,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Nightshade', target: 'Umbral Pigment' },
      description: 'Mill Nightshade into Umbral Pigment (50% success rate, 0.25 average yield)',
      venue: 'Nightshade (i:171315) → Umbral Pigment (i:173056) [1 → 0.25]',
      reagents: [{ itemId: 171315, quantity: 1 }],
      derivatives: [{ itemId: 173056, quantity: 0.25 }],
    },
    {
      expansion: 'SL',
      rank: 2,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Luminous Pigment', target: 'Widowbloom' },
      description: 'Mill Widowbloom into Luminous Pigment (35% success rate, 0.105 average yield)',
      venue: 'Widowbloom (i:168583) → Luminous Pigment (i:173057) [1 → 0.105]',
      reagents: [{ itemId: 168583, quantity: 1 }],
      derivatives: [{ itemId: 173057, quantity: 0.105 }],
    },
    {
      expansion: 'SL',
      rank: 3,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'First Flower', target: 'Tranquil Pigment' },
      description: 'Mill First Flower into Tranquil Pigment (100% success rate, 0.5 average yield - best source)',
      venue: 'First Flower (i:187699) → Tranquil Pigment (i:175788) [1 → 0.5]',
      reagents: [{ itemId: 187699, quantity: 1 }],
      derivatives: [{ itemId: 175788, quantity: 0.5 }],
    },

    // ========================================================================
    // DRAGONFLIGHT - Multi-Quality Pigments
    // ========================================================================
    {
      expansion: 'DF',
      rank: 1,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Hochenblume *', target: 'Shimmering Pigment *' },
      description: 'Mill Hochenblume (Quality 1) into Shimmering Pigment (Quality 1) (100% success rate, 0.7 average yield)',
      venue: 'Hochenblume * (i:191460) → Shimmering Pigment * (i:198421) [1 → 0.7]',
      reagents: [{ itemId: 191460, quantity: 1 }],
      derivatives: [{ itemId: 198421, quantity: 0.7 }],
    },
    {
      expansion: 'DF',
      rank: 1,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Hochenblume **', target: 'Shimmering Pigment **' },
      description: 'Mill Hochenblume (Quality 2) into Shimmering Pigment (Quality 2) (100% success rate, 0.7 average yield)',
      venue: 'Hochenblume ** (i:191461) → Shimmering Pigment ** (i:198422) [1 → 0.7]',
      reagents: [{ itemId: 191461, quantity: 1 }],
      derivatives: [{ itemId: 198422, quantity: 0.7 }],
    },
    {
      expansion: 'DF',
      rank: 1,
      profession: 'Inscription',
      createdBy: 'TSM',
      updatedBy: 'TSM',
      ticker: 'INSC',
      names: { source: 'Hochenblume ***', target: 'Shimmering Pigment ***' },
      description: 'Mill Hochenblume (Quality 3) into Shimmering Pigment (Quality 3) (100% success rate, 0.7 average yield)',
      venue: 'Hochenblume *** (i:191462) → Shimmering Pigment *** (i:198423) [1 → 0.7]',
      reagents: [{ itemId: 191462, quantity: 1 }],
      derivatives: [{ itemId: 198423, quantity: 0.7 }],
    },
  ],
};
