export enum APP_LABELS {
  A = 'auctions',
  CH = 'characters',
  CMNW = 'cmnw',
  C = 'contracts',
  D = 'dma',
  GOLD = 'gold',
  G = 'guilds',
  I = 'items',
  K = 'keys',
  L = 'ladder',
  M = 'market',
  O = 'osint',
  R = 'realms',
  V = 'valuations',
  WCL = 'warcraft-logs',
  W = 'wowprogress',
}
