name: Create OSINT Release Image

on:
  push:
    branches: [ master ]
    paths:
      - 'apps/osint/**'
      - 'libs/*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Tag new release
        uses: butlerlogic/action-autotag@stable
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/alexzedim/osint
          tags: |
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.version }}
          labels: |
            org.opencontainers.image.title=OSINT
            org.opencontainers.image.vendor=AlexZeDim
            org.opencontainers.image.url=https://i.imgur.com/CY0Kqy3.png
            org.opencontainers.image.source=https://github.com/AlexZeDim/cmnw

      - name: Login to Github Packages
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build & Push (GHCR)
        uses: docker/build-push-action@v4.1.1
        with:
          file: ./apps/osint/arm64.Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/alexzedim/osint:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CR_PAT=${{ secrets.CR_PAT }}

      - name: Image digest
        run: echo ${{ steps.build-push-action.outputs.digest }}
