name: Create release

on:
  push:
    branches: [ master ]

jobs:
  # define job to build and publish docker image
  publish:
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.4.0

    - name: Login to Github Packages
      uses: docker/login-action@v1.12.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: match-tag-to-package-version
      id: match-tag-to-package-version
      uses: geritol/match-tag-to-package-version@0.2.0
      with:
        TAG_PREFIX: v

    - name: Build & Push (GHCR)
      uses: docker/build-push-action@v2.9.0
      with:
        file: ./Dockerfile
        push: true
        tags: ghcr.io/alexzedim/cmnw:${{ steps.match-tag-to-package-version.outputs.PACKAGE_VERSION }}
        build-args: |
          CR_PAT=${{ secrets.CR_PAT }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
