name: Create Characters Development Image

on:
  push:
    branches: [ develop ]
    paths:
      - 'apps/characters/**'
      - 'libs/**'

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest #  buildjet-8vcpu-ubuntu-2204-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 2

      - name: Tag new release
        uses: butlerlogic/action-autotag@stable
        env:
          GITHUB_TOKEN: ${{ secrets.CR_PAT }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/alexzedim/characters
          tags: |
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.version }}
          labels: |
            org.opencontainers.image.title=Characters
            org.opencontainers.image.vendor=AlexZeDim
            org.opencontainers.image.url=https://raw.githubusercontent.com/AlexZeDim/cmnw-next/master/public/static/cmnw.png
            org.opencontainers.image.source=https://github.com/AlexZeDim/cmnw

      - name: Login to Github Packages
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build & Push (GHCR)
        uses: docker/build-push-action@v4.1.1
        with:
          file: ./apps/characters/Dockerfile
          push: true
          tags: ghcr.io/alexzedim/characters:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CR_PAT=${{ secrets.CR_PAT }}

      - name: Image digest
        run: echo ${{ steps.build-push-action.outputs.digest }}
