name: Create Auctions Development Image

on:
  push:
    branches: [ develop ]
    paths:
      - 'apps/auctions/**'
      - 'libs/**'

jobs:
  publish:
    name: publish
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.15'
          cache: 'yarn' # Optional: to cache npm dependencies

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/alexzedim/auctions
          tags: |
            type=semver,pattern={{major}}.{{minor}},value=${{ inputs.version }}
          labels: |
            org.opencontainers.image.title = "Auctions"
            org.opencontainers.image.vendor = "alexzedim"
            org.opencontainers.image.url = "https://raw.githubusercontent.com/alexzedim/cmnw-next/master/public/static/cmnw.png"
            org.opencontainers.image.source = "https://github.com/alexzedim/cmnw"
            org.opencontainers.image.licenses = "MPL 2.0"
            org.opencontainers.image.description = "CMNW"

      - name: Login to Github Packages
        uses: docker/login-action@v2.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build & Push (GHCR)
        uses: docker/build-push-action@v4.1.1
        with:
          file: ./apps/auctions/Dockerfile
          push: true
          tags: ghcr.io/alexzedim/auctions:latest
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CR_PAT=${{ secrets.CR_PAT }}

      - name: Image digest
        run: echo ${{ steps.build-push-action.outputs.digest }}
